# Generated by Django 5.2.6 on 2025-09-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('url_foto', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rol')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_users', to='backend.user')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
